import fetch from 'node-fetch';

async function setWebhook() {
  try {
    const token = process.env.TELEGRAM_BOT_TOKEN;
    if (!token) {
      console.error('TELEGRAM_BOT_TOKEN is required!');
      return;
    }
    
    // For Replit, we'll use the public URL generated by Replit 
    // This will be in the format https://telegram-mini-app-guljansmm.replit.app
    const publicUrl = "https://telegram-mini-app-guljansmm.replit.app";
    const webhookUrl = `${publicUrl}/api/telegram-webhook`;
    
    console.log(`Setting webhook to: ${webhookUrl}`);
    
    // Delete any existing webhook
    const deleteUrl = `https://api.telegram.org/bot${token}/deleteWebhook`;
    await fetch(deleteUrl);
    
    // Set the new webhook
    const setUrl = `https://api.telegram.org/bot${token}/setWebhook?url=${encodeURIComponent(webhookUrl)}`;
    const response = await fetch(setUrl);
    const result = await response.json();
    
    if (result.ok) {
      console.log('✅ Webhook set successfully!');
      
      // Get webhook info to verify
      const infoUrl = `https://api.telegram.org/bot${token}/getWebhookInfo`;
      const infoResponse = await fetch(infoUrl);
      const infoResult = await infoResponse.json();
      
      console.log('Current webhook info:');
      console.log(JSON.stringify(infoResult, null, 2));
    } else {
      console.error('❌ Failed to set webhook:', result.description);
    }
  } catch (error) {
    console.error('Error setting webhook:', error);
  }
}

// Run the function
setWebhook();